### PR TITLE
added conditional for swift not to run iface if its has controller on…

### PR DESCRIPTION
**Pull request by jdextercsc**
PLAY [Swift Interface Configuration] ******************************************

GATHERING FACTS ***************************************************************
ok: [controller-3]
ok: [controller-2]
ok: [controller-1]

TASK: [iface | deploy network interface config file] **************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | bring up deployed interface] ***********************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | deploy network interface config file] **************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | bring up deployed interface] ***********************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | deploy network interface config file] **************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | bring up deployed interface] ***********************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | deploy network interface config file] **************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | bring up deployed interface] ***********************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | deploy network interface config file] **************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

TASK: [iface | bring up deployed interface] ***********************************
skipping: [controller-1]
skipping: [controller-2]
skipping: [controller-3]

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Requested the conditional be added to the last iface role in the swift.yml palybook.

**Comment by mtnbikenc** [comment]
Code review :+1:

**Comment by wgd3** [comment]
Looks good

**Comment by adean20csc** [comment]
Good  :+1:

**Pull request merged**
