### PR TITLE
Added cluster-constraints for cinder

### PR DESCRIPTION
**Pull request by adean20csc**

### CODE REVIEW

**Comment by jcpowermac** [comment]
Looks good :+1: waiting for travis.

**Comment by mtnbikenc** [comment]
Need to add a constraint for keystone.  Anything that is part of 'collapsed' we put in.

```
pcs constraint order start keystone-clone then cinder-api-clone
```

**Comment by adean20csc** [comment]
Added Keystone constraint

**Comment by mtnbikenc** [comment]
After Travis passes, I'm :+1:

**Pull request merged**
