### PR TITLE
Update of slimer to include the kilo changes

### PR DESCRIPTION
**Pull request by jdextercsc**

### CODE REVIEW

**Comment by tjmcs** [comment]
So does this switch everything over to only support kilo or are we supporting both juno and kilo (with some sort of switch to determine which the user is interested in deploying)?  Haven't had time to check this out, but I think it's something worth discussing...

**Comment by jdextercsc** [comment]
In the group_vars/common.yml we have a variable called "openstack_release".  setting it to juno or kilo will switch between the 2 versions during the install

`openstack_release: juno`
or 
`openstack_release: kilo`

**Comment by jcpowermac** [comment]
Looks good to me :+1:

**Comment by adean20csc** [comment]
Good  :+1:

**Pull request merged**
