### PR TITLE
fixes to neutron:

### PR DESCRIPTION
**Pull request by jdextercsc**
rabbitmq login and password info on compute nodes
Adds udp 4789 to the iptables list

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Requested code consistency updates and test results.

**Comment by jdextercsc** [comment]
Full run was tested after the update. 

```
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:4789 /*  neutron tunnels */
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:4789 /*  neutron tunnels */
```

**Comment by wgd3** [comment]
:ok_hand:

**Comment by mtnbikenc** [comment]
Code review :+1:

**Pull request merged**
