### PR TITLE
Iptables module

### PR DESCRIPTION
**Pull request by jdextercsc**
## Pull Request for NGA-449
# Documentation

```
module: iptables
short_description: appends iptables rules to a run time configuration and saves the resulting iptables rule chain to disk
options:
    protocol:
        required: true
        choices: ['tcp', 'udp']
    # state:
    #     required: true
    #     choices: ['absent', 'present']
    port:
        required: true
        description: a list of ports to open
    source:
        required: false
        description: the IP address to filter for source of packets in form of CIDR notition XX.XX.XX.XX/YY
    dest:
        required: false
        description: the IP address to filter for destination of packets in form of CIDR notition XX.XX.XX.XX/YY
    comment:
        required: false
        description: a string containing a descriptive comment about the rule.
    chain:
        required: false
        default: 'INPUT'
```
# Testing
## Original Iptables Configuration

```
[root@controller-1 ~]# cat /etc/sysconfig/iptables
# Generated by iptables-save v1.4.21 on Wed Oct  7 13:56:49 2015
*filter
:INPUT ACCEPT [835:494702]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [526:44144]
COMMIT
# Completed on Wed Oct  7 13:56:49 2015
[root@controller-1 ~]#
```
## Test Module

```
[root@ansible slimer]# cat test.yml
- name: test iptable module test
  hosts: test
  tasks:
    - name: print iptables
      command: iptables -nL

    - name: only port and protocol
      iptables:
        port: 8081
        protocol: tcp
      ignore_errors: true

    - name: check to see if its changed.
      iptables:
        port: 8081
        protocol: tcp
      ignore_errors: true

    - name: multiple ports
      iptables:
        port: [8081,8000]
        protocol: tcp
      ignore_errors: true

    - name: single port wih source and dest
      iptables:
        port: 22
        protocol: tcp
        source: "172.17.0.0/16"
        dest: "{{ansible_default_ipv4.address}}"
      ignore_errors: true

    - name: print iptables end
      command: iptables -nL
```
## test output

```
TASK: [print iptables end] ****************************************************
changed: [controller-1] => {"changed": true, "cmd": ["iptables", "-nL"], "delta": "0:00:00.005549", "end": "2015-10-07 14:13:36.710816", "rc": 0, "start": "2015-10-07 14:13:36.705267", "stderr": "", "stdout": "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination         \nACCEPT     tcp  --  172.17.0.0/16        192.168.100.113      tcp dpt:22\nACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 8081,8000\nACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8081\n\nChain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination         ", "warnings": []}

PLAY RECAP ********************************************************************
controller-1               : ok=7    changed=2    unreachable=0    failed=0

[root@ansible slimer]# vim library/iptables.py
[root@ansible slimer]# ansible-playbook test.yml -v

PLAY [test iptable module test] ***********************************************

GATHERING FACTS ***************************************************************
ok: [controller-1]

TASK: [print iptables] ********************************************************
changed: [controller-1] => {"changed": true, "cmd": ["iptables", "-nL"], "delta": "0:00:00.005739", "end": "2015-10-07 14:16:27.380425", "rc": 0, "start": "2015-10-07 14:16:27.374686", "stderr": "", "stdout": "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination         ", "warnings": []}

TASK: [only port and protocol] ************************************************
changed: [controller-1] => {"changed": true, "msg": "INPUT -p tcp --dport 8081"}

TASK: [check to see if its changed.] ******************************************
ok: [controller-1] => {"changed": false, "msg": "rule INPUT -p tcp --dport 8081 already exists."}

TASK: [multiple ports] ********************************************************
changed: [controller-1] => {"changed": true, "msg": "INPUT -p tcp -m multiport --dport 8081,8000"}

TASK: [single port wih source and dest] ***************************************
changed: [controller-1] => {"changed": true, "msg": "INPUT -p tcp --dport 22 -s 172.17.0.0/16 -d 192.168.100.113"}

TASK: [print iptables end] ****************************************************
changed: [controller-1] => {"changed": true, "cmd": ["iptables", "-nL"], "delta": "0:00:00.005950", "end": "2015-10-07 14:16:28.730173", "rc": 0, "start": "2015-10-07 14:16:28.724223", "stderr": "", "stdout": "Chain INPUT (policy ACCEPT)\ntarget     prot opt source               destination         \nACCEPT     tcp  --  172.17.0.0/16        192.168.100.113      tcp dpt:22\nACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 8081,8000\nACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8081\n\nChain FORWARD (policy ACCEPT)\ntarget     prot opt source               destination         \n\nChain OUTPUT (policy ACCEPT)\ntarget     prot opt source               destination         ", "warnings": []}

PLAY RECAP ********************************************************************
controller-1               : ok=7    changed=5    unreachable=0    failed=0
```
## final iptables config

```
[root@controller-1 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  172.17.0.0/16        controller-1.novalocal  tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             multiport dports tproxy,irdmi
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:tproxy

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

### CODE REVIEW

**Comment by mtnbikenc** [comment]
Working on the review.  I'll compile my comments into one.

**Comment by jdextercsc** [comment]
retested after fixes [root@ansible slimer]# ansible-playbook test.yml

```
PLAY [test iptable module test] ***********************************************

GATHERING FACTS ***************************************************************
ok: [controller-1]

TASK: [print iptables] ********************************************************
changed: [controller-1]

TASK: [only port and protocol] ************************************************
changed: [controller-1]

TASK: [check to see if its changed.] ******************************************
ok: [controller-1]

TASK: [multiple ports] ********************************************************
changed: [controller-1]

TASK: [single port wih source and dest] ***************************************
changed: [controller-1]

TASK: [print iptables end] ****************************************************
changed: [controller-1]

PLAY RECAP ********************************************************************
controller-1               : ok=7    changed=5    unreachable=0    failed=0
```

**Comment by mtnbikenc** [comment]
Code review, looks great :+1:

**Comment by jcpowermac** [comment]
@jdextercsc in a future update I would like to see exception handling and the use of the [python-iptables](https://github.com/ldx/python-iptables) instead of forking iptables.
For now ... code review :+1:

**Pull request merged**
