### PR TITLE
Horizon: moved to juno.yml, with include in main.yml

### PR DESCRIPTION
**Pull request by jdextercsc**

### CODE REVIEW

**Comment by mtnbikenc** [comment]
If there was no difference before in releases, do we need to add the release branching to horizon?

**Comment by jcpowermac** [comment]
@mtnbikenc I thought that was what we decided to do.  This is for consistency between roles and  _if_ kilo, liberty or future release needed a change.

**Comment by mtnbikenc** [comment]
I'm fine with that.  :+1:

**Comment by jcpowermac** [comment]
Code review :+1:

**Pull request merged**
