### PR TITLE
changes after testing

### PR DESCRIPTION
**Pull request by jdextercsc**
changes from 9/8

### CODE REVIEW

**Comment by jdextercsc** [comment]
> 2015-09-10 11:09:09,268 p=44876 u=root |  TASK: [demo | copy image to controller1] >**************************************
> 2015-09-10 11:09:09,315 p=44876 u=root |  fatal: [wiley-ctlr-1] => input file not found at /root/rhel-guest->image-7.1-20150224.0.x86_64.qcow2 or /root/rhel-guest-image-7.1-20150224.0.x86_64.qcow2
> 2015-09-10 11:09:09,316 p=44876 u=root |  FATAL: all hosts have already failed -- aborting
> 2015-09-10 11:09:09,316 p=44876 u=root |  PLAY RECAP >********************************************************************
> 2015-09-10 11:09:09,317 p=44876 u=root |             to retry, use: --limit @/root/site.retry
> 
> 2015-09-10 11:09:09,317 p=44876 u=root |  wiley-cmp-1                : ok=77   changed=56   unreachable=0    failed=0
> 2015-09-10 11:09:09,317 p=44876 u=root |  wiley-ctlr-1               : ok=340  changed=256  unreachable=0    failed=1
> 2015-09-10 11:09:09,318 p=44876 u=root |  wiley-ctlr-2               : ok=344  changed=261  unreachable=0    failed=1
> 2015-09-10 11:09:09,318 p=44876 u=root |  wiley-ctlr-3               : ok=344  changed=261  unreachable=0    failed=1
> 2015-09-10 11:09:09,318 p=44876 u=root |  wiley-scale-1              : ok=28   changed=24   unreachable=0    failed=0
> 2015-09-10 11:09:09,318 p=44876 u=root |  wiley-scale-2              : ok=28   changed=24   unreachable=0    failed=0
> 2015-09-10 11:09:09,319 p=44876 u=root |  wiley-scale-3              : ok=28   changed=24   unreachable=0    failed=0
> 2015-09-10 11:09:09,319 p=44876 u=root |  wiley-swift-1              : ok=79   changed=54   unreachable=0    failed=0
> 2015-09-10 11:09:09,319 p=44876 u=root |  wiley-swift-2              : ok=79   changed=54   unreachable=0    failed=0
> 2015-09-10 11:09:09,319 p=44876 u=root |  wiley-swift-3              : ok=79   changed=54   unreachable=0    failed=0```

Failed on demo, install worked

**Comment by jcpowermac** [comment]
New task `use pool`

```
2015-09-08 14:03:53,108 p=14751 u=root |  TASK: [subscription-manager | use pool] ***************************************
2015-09-08 14:03:53,171 p=14751 u=root |  <172.17.16.70> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,176 p=14751 u=root |  <172.17.16.71> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,179 p=14751 u=root |  <172.17.16.72> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,180 p=14751 u=root |  <172.17.16.73> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,182 p=14751 u=root |  <172.17.16.75> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,184 p=14751 u=root |  <172.17.16.76> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,186 p=14751 u=root |  <172.17.16.77> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,192 p=14751 u=root |  <172.17.16.74> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:53,202 p=14751 u=root |  <172.17.16.78> REMOTE_MODULE command subscription-manager attach --pool 8a85f9814a5f6740014a5f71c4ec328b
2015-09-08 14:03:59,271 p=14751 u=root |  changed: [wiley-swift-1] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:05.927117", "end": "2015-09-08 12:03:59.103282", "rc": 0, "start": "2015-09-08 12:03:53.176165", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:03:59,747 p=14751 u=root |  changed: [wiley-ctlr-3] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:06.417854", "end": "2015-09-08 12:03:58.342113", "rc": 0, "start": "2015-09-08 12:03:51.924259", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:01,085 p=14751 u=root |  changed: [wiley-swift-3] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:07.673566", "end": "2015-09-08 12:04:01.173034", "rc": 0, "start": "2015-09-08 12:03:53.499468", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:03,853 p=14751 u=root |  changed: [wiley-scale-2] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:10.415224", "end": "2015-09-08 12:04:03.935183", "rc": 0, "start": "2015-09-08 12:03:53.519959", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:04,038 p=14751 u=root |  changed: [wiley-scale-1] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:10.616101", "end": "2015-09-08 12:03:21.926223", "rc": 0, "start": "2015-09-08 12:03:11.310122", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:06,969 p=14751 u=root |  changed: [wiley-ctlr-2] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:13.647578", "end": "2015-09-08 12:04:18.455457", "rc": 0, "start": "2015-09-08 12:04:04.807879", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:10,943 p=14751 u=root |  changed: [wiley-cmp-1] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:17.525619", "end": "2015-09-08 12:04:11.359238", "rc": 0, "start": "2015-09-08 12:03:53.833619", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:13,311 p=14751 u=root |  changed: [wiley-ctlr-1] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:19.906237", "end": "2015-09-08 12:04:13.303868", "rc": 0, "start": "2015-09-08 12:03:53.397631", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
2015-09-08 14:04:18,703 p=14751 u=root |  changed: [wiley-swift-2] => {"changed": true, "cmd": ["subscription-manager", "attach", "--pool", "8a85f9814a5f6740014a5f71c4ec328b"], "delta": "0:00:25.376343", "end": "2015-09-08 12:04:18.429376", "rc": 0, "start": "2015-09-08 12:03:53.053033", "stderr": "", "stdout": "Successfully attached a subscription for: Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR", "warnings": []}
```

**Comment by jcpowermac** [comment]
Code review :+1:

**Comment by mtnbikenc** [comment]
Code review :+1:

**Pull request merged**
